import Prism from "prismjs/components/prism-core.js";
import "prismjs/components/prism-clike.js";
import "prismjs/components/prism-markup.js";
import "prismjs/components/prism-markup-templating";
import "prismjs/components/prism-sql.js";
import "prismjs/components/prism-php.js";
import "prismjs/components/prism-php-extras.js";
import "prismjs/components/prism-javascript.js";
import "prismjs/components/prism-typescript.js";
// import "prismjs/components/prism-go.js";
// import "prismjs/components/prism-rust.js";
import "prismjs/components/prism-css.js";
import "prismjs/components/prism-css-extras.js";
import "prismjs/components/prism-scss.js";
import "prismjs/components/prism-twig.js";
import "prismjs/components/prism-bash.js";
import "prismjs/components/prism-batch.js";
import "prismjs/components/prism-docker.js";
import "prismjs/components/prism-http.js";
import "prismjs/components/prism-git.js";
import "prismjs/components/prism-ini.js";
import "prismjs/components/prism-json.js";
import "prismjs/components/prism-yaml.js";
// import "prismjs/components/prism-makefile.js";
import "prismjs/components/prism-markdown";
import "prismjs/components/prism-apacheconf.js";
// import "prismjs/components/prism-nginx.js";

Prism.languages.dos = Prism.languages.batch;
Prism.languages.apache = Prism.languages.apacheconf;

export default Prism;
